### ISSUE TITLE
ts.isNamedTupleMember is not a function

### ISSUE THREAD

**Issue by drashti4** [frandiox/vue-use-stripe#4]
I cloned repo and did `npm install `then `npm run build `but got following error.

`TypeError: Could not load /home/drashti/Documents/vue-use-stripe/src/use-stripe.ts (imported by src/index.ts): ts.isNamedTupleMember is not a function`

   ` at DeclarationScope.convertTypeNode (/home/drashti/Documents/vue-use-stripe/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js:770:16)
    at DeclarationScope.convertMembers (/home/drashti/Documents/vue-use-stripe/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js:715:22)
    at DeclarationScope.convertTypeNode (/home/drashti/Documents/vue-use-stripe/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js:758:25)
    at Transformer.convertTypeAliasDeclaration (/home/drashti/Documents/vue-use-stripe/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js:1163:15)
    at Transformer.convertStatement (/home/drashti/Documents/vue-use-stripe/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js:1079:25)
    at new Transformer (/home/drashti/Documents/vue-use-stripe/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js:999:18)
    at transformFile (/home/drashti/Documents/vue-use-stripe/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js:1319:29)
    at Object.writeFile (/home/drashti/Documents/vue-use-stripe/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js:1390:29)
    at Object.writeFile (/home/drashti/Documents/vue-use-stripe/node_modules/typescript/lib/typescript.js:16614:14)
    at printSourceFileOrBundle (/home/drashti/Documents/vue-use-stripe/node_modules/typescript/lib/typescript.js:94837:16)
`

**Comment by y-danny** [comment]
是否和node 版本有关
